# To install:
#
#     pip install pre-commit
#
# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
ci:
  autofix_commit_msg: "ci(pre-commit): autofix"
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
        args: ["-c", ".markdownlint.yaml", "--fix"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        exclude: "(.rviz|.param.yaml)"

  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: v0.2.0
    hooks:
      - id: prettier-package-xml
      - id: sort-package-xml

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.15
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: uncrustify
        name: ament_uncrustify
        description: Formats C/CPP code
        language: docker_image
        files: \.(c|cc|cxx|cpp|h|hpp|hxx|m)$
        entry: ros:galactic ament_uncrustify --reformat

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length=100"]

exclude: ".svg"
