vehicle_voice_alert_system:
  ros__parameters:
    ignore_emergency_stoppped: false
    manual_driving_bgm: true # param for enable bgm to play when manual driving
    driving_velocity_threshold: 0.2 # param for the threshold to play the running bgm
    mute_timeout: # Param for to mute for a period after the announce
      restart_engage: 5.0
      stop_reason: 20.0
      turn_signal: 5.0
      in_emergency: 30.0
      driving_bgm: 0.0
    skip_default_voice: true # Param for skip playing default voice, if the voice is not found in the primary_voice_folder_path
