name: update beta branch

env:
  SYNC_BRANCH_PREFIX: update-beta-branch

jobs:
  update-beta-branch:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Set BASE_BRANCH
        run: |
          echo "BASE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_BRANCH }}
          fetch-depth: 0

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Install vcstool
        run: |
          sudo apt update && sudo apt install curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update && sudo apt-get install python3-vcstool
      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/.insteadOf 'https://github.com/'
          git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/.insteadOf 'git@github.com:'
      - name: Set git config
        run: |
          git config --local user.email "actions@example.com"
          git config --local user.name "Github Actions"
      - name: Run update script
        run: ./.github/scripts/update_beta_branches.sh
        shell: bash
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore: update beta branch for ${{ env.BASE_BRANCH }}"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          signoff: false
          base: ${{ env.BASE_BRANCH }}
          branch: ${{ env.SYNC_BRANCH_PREFIX }}/${{ env.BASE_BRANCH }}
          delete-branch: true
          title: "chore: update beta branch for ${{ env.BASE_BRANCH }}"
          body: |
            update beta branch for ${{ env.BASE_BRANCH }}
          labels: |
            bot
            update-beta-branch
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"
